# Generated by Django 2.2.6 on 2019-10-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='hire_date',
        ),
    ]
