# Generated by Django 2.2.6 on 2019-10-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191013_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='bid_price',
        ),
        migrations.RemoveField(
            model_name='books',
            name='photo_6',
        ),
        migrations.AddField(
            model_name='books',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
