# Generated by Django 2.2.6 on 2019-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191025_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
